# Generated by Django 3.2.9 on 2021-11-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211114_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='suername',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
