# Generated by Django 3.2.9 on 2021-11-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_suername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='suername',
            new_name='uername',
        ),
    ]
