# Generated by Django 3.2.9 on 2021-11-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_suername_chat_uername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='uername',
            new_name='username',
        ),
    ]
