# Generated by Django 3.2.9 on 2021-11-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211116_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='at',
        ),
    ]
